# Generated by Django 5.2.8 on 2025-11-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('qpi', models.FloatField()),
                ('year', models.IntegerField()),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
